### ISSUE TITLE
Exception if service do not include performance data

### ISSUE THREAD

**Issue by thenodon** [opsdis/icinga2-exporter#2]
Need to verify that the structure include performance_data 
` serivce_attrs['attrs']['last_check_result']['performance_data']`
Exception is:
 [2019-09-02 09:22:06,104] ERROR in app: Exception on /metrics [GET]
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/.local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/icinga2-exporter/icinga2_exporter/proxy.py", line 48, in get_metrics
    monitor_data.get_perfdata()
  File "/home/ubuntu/icinga2-exporter/icinga2_exporter/perfdata.py", line 63, in get_perfdata
    for perf_string in serivce_attrs['attrs']['last_check_result']['performance_data']:
TypeError: 'NoneType' object is not iterable

**Comment by thenodon** [comment]
The problem was a need to check if performance_data was `null` in the json or rather None when transformed to dictonary
