### ISSUE TITLE
Show permission error instead of json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by Nudin** [opsdis/icinga2-exporter#21]
Hi, I get a JSONDecodeError. What am I doing wrong? I'm using the latest version from this repo and the example configuration.
```
[2021-07-23 11:36:08,761] ERROR in app: Exception on request GET /metrics
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/quart/app.py", line 1451, in handle_request
    return await self.full_dispatch_request(request_context)
  File "/usr/local/lib/python3.7/dist-packages/quart/app.py", line 1473, in full_dispatch_request
    result = await self.handle_user_exception(error)
  File "/usr/local/lib/python3.7/dist-packages/quart/app.py", line 892, in handle_user_exception
    raise error
  File "/usr/local/lib/python3.7/dist-packages/quart/app.py", line 1471, in full_dispatch_request
    result = await self.dispatch_request(request_context)
  File "/usr/local/lib/python3.7/dist-packages/quart/app.py", line 1519, in dispatch_request
    return await handler(**request_.view_args)
  File "/usr/local/lib/python3.7/dist-packages/icinga2_exporter/proxy.py", line 56, in get_ametrics
    await fetch_perfdata_task
  File "/usr/local/lib/python3.7/dist-packages/icinga2_exporter/perfdata.py", line 54, in get_perfdata
    data_json = await self.monitor.async_get_perfdata(self.query_hostname)
  File "/usr/local/lib/python3.7/dist-packages/icinga2_exporter/monitorconnection.py", line 162, in async_get_perfdata
    data_json = await self.async_post(self.url_query_service_perfdata, body)
  File "/usr/local/lib/python3.7/dist-packages/icinga2_exporter/monitorconnection.py", line 180, in async_post
    return json.loads(re)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by Nudin** [comment]
I forgot to restart icinga2 and therefore got a permission error. Would be nice if that could be displayed.

**Comment by thenodon** [comment]
Thanks for reporting the issue. I will improve the exception handling related to connecting to the icinga2 instance. This is both related to your reported issue, but also to timeouts and not resolving the server. In all cases a warning will be logged and an empty response will be returned with http status 500, https://prometheus.io/docs/instrumenting/writing_exporters/#failed-scrapes. An empty response can also be returned if the request is a none existing host, but than the http status will be 200.

**Comment by thenodon** [comment]
Please try the new 1.2.0 version where the error handling is fixed.
