### ISSUE TITLE
Exception if host does not have custom properties

### ISSUE THREAD

**Issue by skupjoe** [opsdis/icinga2-exporter#4]
Thanks for the plugin! I tried adding my first test host and with a single ping service, no custom properties on either the Host or the Service, and I see this error:

```
icinga2-exporter    | [2020-07-10 09:59:10,491] ERROR in app: Exception on request GET /metrics                                                                                                              
icinga2-exporter    | Traceback (most recent call last):                                                                                                                                                     
icinga2-exporter    |   File "/usr/local/lib/python3.7/site-packages/quart/app.py", line 1451, in handle_request                                                                                             
icinga2-exporter    |     return await self.full_dispatch_request(request_context)                                                                                                                           
icinga2-exporter    |   File "/usr/local/lib/python3.7/site-packages/quart/app.py", line 1473, in full_dispatch_request                                                                                      
icinga2-exporter    |     result = await self.handle_user_exception(error)                                                                                                                                   
icinga2-exporter    |   File "/usr/local/lib/python3.7/site-packages/quart/app.py", line 892, in handle_user_exception                                                                                       
icinga2-exporter    |     raise error                                                                                                                                                                        
icinga2-exporter    |   File "/usr/local/lib/python3.7/site-packages/quart/app.py", line 1471, in full_dispatch_request                                                                                      
icinga2-exporter    |     result = await self.dispatch_request(request_context)                                                                                                                              
icinga2-exporter    |   File "/usr/local/lib/python3.7/site-packages/quart/app.py", line 1519, in dispatch_request                                                                                           
icinga2-exporter    |     return await handler(**request_.view_args)                                                                                                                                         
icinga2-exporter    |   File "/usr/local/lib/python3.7/site-packages/icinga2_exporter/proxy.py", line 49, in get_ametrics                                                                                    
icinga2-exporter    |     await asyncio.get_event_loop().create_task(monitor_data.get_perfdata())                                                                                                            
icinga2-exporter    |   File "/usr/local/lib/python3.7/site-packages/icinga2_exporter/perfdata.py", line 63, in get_perfdata                                                                                 
icinga2-exporter    |     labels.update(Perfdata.get_host_custom_vars(serivce_attrs))                                                                                                                        
icinga2-exporter    |   File "/usr/local/lib/python3.7/site-packages/icinga2_exporter/perfdata.py", line 141, in get_host_custom_vars                                                                        
icinga2-exporter    |     for custom_vars_key, custom_vars_value in serivce_attrs['joins']['host']['vars'].items():                                                                                          
icinga2-exporter    | AttributeError: 'NoneType' object has no attribute 'items'   
```

And the webserver returns a 500 error.

**Comment by skupjoe** [comment]
Also, looks like `serivce_attrs` dict is misspelled 😜

**Comment by thenodon** [comment]
@skupjoe thanks for the bug report. Will fix it :)

**Comment by thenodon** [comment]
The fix is merged into master. Hope it works better for you @skupjoe. And once again thanks for your feedback and interest in the project.
