### ISSUE TITLE
host_custom_vars config is not optional

### ISSUE THREAD

**Issue by skupjoe** [opsdis/icinga2-exporter#5]
It's mentioned on your readme that host custom vars to labels config is an optional parameter:

> Optional icinga2-exporter can be configured to add specific custom variables configured on the host.

However, when I omit this block from my `config.yml` (I'm trying to workaround issue #4) I get a separate exception:

```
icinga2-exporter    | {"timestamp": "2020-07-10T10:06:40.469733Z", "level": "INFO", "name": "icinga2-exporter", "message": "Collect metrics", "target": "172.16.11.62"}
icinga2-exporter    | [2020-07-10 10:06:40,469] ERROR in app: Exception on request GET /metrics
icinga2-exporter    | Traceback (most recent call last):
icinga2-exporter    |   File "/usr/local/lib/python3.7/site-packages/quart/app.py", line 1451, in handle_request
icinga2-exporter    |     return await self.full_dispatch_request(request_context)
icinga2-exporter    |   File "/usr/local/lib/python3.7/site-packages/quart/app.py", line 1473, in full_dispatch_request
icinga2-exporter    |     result = await self.handle_user_exception(error)
icinga2-exporter    |   File "/usr/local/lib/python3.7/site-packages/quart/app.py", line 892, in handle_user_exception
icinga2-exporter    |     raise error
icinga2-exporter    |   File "/usr/local/lib/python3.7/site-packages/quart/app.py", line 1471, in full_dispatch_request
icinga2-exporter    |     result = await self.dispatch_request(request_context)
icinga2-exporter    |   File "/usr/local/lib/python3.7/site-packages/quart/app.py", line 1519, in dispatch_request
icinga2-exporter    |     return await handler(**request_.view_args)
icinga2-exporter    |   File "/usr/local/lib/python3.7/site-packages/icinga2_exporter/proxy.py", line 46, in get_ametrics
icinga2-exporter    |     monitor_data = Perfdata(monitorconnection.MonitorConfig(), target)
icinga2-exporter    |   File "/usr/local/lib/python3.7/site-packages/icinga2_exporter/perfdata.py", line 41, in __init__
icinga2-exporter    |     self.configured_labels = monitor.get_labels()
icinga2-exporter    |   File "/usr/local/lib/python3.7/site-packages/icinga2_exporter/monitorconnection.py", line 102, in get_labels
icinga2-exporter    |     for label in self.labels:
icinga2-exporter    | TypeError: 'NoneType' object is not iterable
icinga2-exporter    | [2020-07-10 10:06:40,470] 169.234.220.180:54954 GET /metrics 1.1 500 126 1600
icinga2             | 172.31.19.203 - - [10/Jul/2020:10:06:44 +0000] "GET /v2/health-check HTTP/1.1"
```

**Comment by skupjoe** [comment]
OK-looks like if you remove `host_custom_vars:` entirely the error goes away. I just had it so nothing was under this block.
