### ISSUE TITLE
Python 3.8: ValueError: Invalid format '(timestamp) (level) (name) (message)' for '%' style

### ISSUE THREAD

**Issue by msafdal** [opsdis/icinga2-exporter#7]
icinga2-exporter does not work with Python 3.8.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/src/app/icinga2_exporter/__main__.py", line 26, in <module>
    main.start()
  File "/usr/src/app/icinga2_exporter/main.py", line 58, in start
    log.configure_logger(configuration)
  File "/usr/src/app/icinga2_exporter/log.py", line 38, in configure_logger
    formatter = CustomJsonFormatter('(timestamp) (level) (name) (message)')
  File "/usr/local/lib/python3.8/site-packages/pythonjsonlogger/jsonlogger.py", line 112, in __init__
    logging.Formatter.__init__(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/logging/__init__.py", line 576, in __init__
    self._style.validate()
  File "/usr/local/lib/python3.8/logging/__init__.py", line 429, in validate
    raise ValueError("Invalid format '%s' for '%s' style" % (self._fmt, self.default_format[0]))
ValueError: Invalid format '(timestamp) (level) (name) (message)' for '%' style
```
Caused by changes in 3.8:
https://docs.python.org/3/library/logging.html#logging.Formatter

> Changed in version 3.8: The validate parameter was added. Incorrect or mismatched style and fmt will raise a ValueError. For example: logging.Formatter('%(asctime)s - %(message)s', style='{').

Sugested resolution:
Update https://github.com/opsdis/icinga2-exporter/blob/master/icinga2_exporter/log.py#L38

**Comment by thenodon** [comment]
Fix in commit cb35161
